config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {:registrations => "registrations"}
  resources :users, only: [:index]
  root 'home#index'
  #root 'documents#index'
  resources :documents
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates_presence_of :name, :email, :password, message: "Ops! Preencha esse Aqui!"
  validates :email, uniqueness: {  message: "Este E-mail já Existe!" }

  default_value_for :deleted, false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  validates_presence_of :title, :file, :user_id, message: "Ops! Preencha esse Aqui!"
  belongs_to :user
  
  mount_uploader :file, FileUploader
end

app/models/user.rb
class User < ApplicationRecord
  #validates_presence_of :email, :password, message: "Ops! Preencha esse Aqui!"
  has_many :documents
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  default_value_for :kind, "client"
  default_value_for :deleted, false

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_account, only: [:edit, :update, :show, :destroy]

  def new
    @account = Account.new
  end

  def create
    nome = params["account"]["name"]
    email = params["account"]["email"]
    password = params["account"]["password"]
    #user = User.new(name: nome, email: email, password: password)
    #user.save
    User.create(name: nome, email: email, password: password)
    #binding.pry
    @account = Account.create(account_params)
    respond_with @account
  end

  def show
    respond_with @account
  end

  def update
    @account.update(account_params)
    respond_with @account
  end

  def destroy
    id = @account.id
    if id == current_user.id
      flash[:notice] = 'Ops!'
      redirect_to accounts_path
    else
      @account.deleted = true
      @account.save
      a = User.find(id)
      a.deleted = true
      a.save
      flash[:notice] = 'Deletado com sucesso!'
      redirect_to accounts_path
    end
  rescue
    flash[:notice] = 'Ops!'
    redirect_to accounts_path
  end

  def index
    if current_user && current_user.kind == "manager"
      @accounts = User.paginate(:page => params[:page], :per_page => 10)
                          .order(created_at: :asc).where(deleted: false)
    else

      @accounts = nil
    end
  end


  private

  def set_account
    if current_user.kind == "manager"
      @account = Account.find(params[:id])
    elsif current_user
      @account = Account.find(current_user.id)
    else
      @account = nil
    end
  end

  def account_params
    params.require(:account).permit( :name, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  respond_to :html

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:edit, :update, :show, :destroy]

  def new
    @document = Document.new
  end

  def create
    @document = Document.create(document_params)
    respond_with @document
  end

  def show
    respond_with @document
  end

  def update
    @document.update(document_params)
    respond_with @document
  end

  def destroy
    @document.destroy
    redirect_to documents_path, alert: "Documento deletado com Sucesso"
  rescue
    redirect_to documents_path, alert: "Não foi possivel deletar o Documento!"
  end

  def index
    if current_user.kind == "manager"
      @documents = Document.paginate(:page => params[:page], :per_page => 10)
                          .order(created_at: :asc)
    else
      @documents = Document.paginate(:page => params[:page], :per_page => 10)
                          .order(created_at: :asc).where(user_id: current_user.id)
    end
  end


  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :file, :description, :user_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  skip_before_filter :require_no_authentication, only: [:new, :create, :index, :update]

  def new
    super
  end

  def create_user
    @user = User.new(:email => params[:email], :password => params[:password], :kind => params[:kind], :name => params[:name] )
    @user.save
    #redirect_to documents_path, alert: "Documento deletado com Sucesso"
  end

  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<% if @accounts.nil? %>
<h1>NADA AQUI!!!!</h1>
<% else %>
<%- model_class = Account -%>
<div class="page-header">
  <h1>Usuários - <%= link_to 'Cadastrar usuário',
              new_account_path,
              :class => 'btn btn-primary' %>
            </h1>
</div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Ações</th>
      </tr>
    </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= link_to account.id, account_path(account) %></td>
            <td><%= account.name %></td>
            <td><%= account.email %></td>
            <td>
              <%= link_to t('.show', :default => t("helpers.links.show")),
                          account_path(account), :class => 'btn btn-default' %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_account_path(account), :class => 'btn btn-default' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          account_path(account),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
  </table>
<% end %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @account.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @account.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/documents/_client.html.erb
<%if @documents.length==0%>
  <h1><br><br>Você não possui nenhum documento!</h1>
<%else%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Titulo</th>
        <th>Descrição</th>
        <th>Baixar Arquivos</th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= document.title %></td>
          <td><%= document.description %></td>
          <td>
            <a href="<%= document.file %>" class="btn btn-info btn-lg">
              <span class="glyphicon glyphicon-cloud-download"></span> Download Arquivo
            </a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br><br>

app/views/documents/_form.html.erb
<%= simple_form_for @document, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :file %>
  <%= f.input :description %>
  <%= f.association :user, prompt: "Selecione o Cliente", collection: User.where(deleted: false).where.not(id: current_user.id)%>


  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                documents_path, :class => 'btn btn-default' %>
<% end %>

app/views/documents/_manager.html.erb
<%if @documents.length==0%>
  <h1>Sem Documentos!</h1>
<%else%>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @documents.each do |document| %>
        <tr>
          <td><%= link_to document.id, document_path(document) %></td>
          <td><%= document.title %></td>
          <td><%= document.description %></td>
          <td>
            <a class="btn btn-primary" href="<%= document.file %>" role="button" download>Download</a>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_document_path(document), :class => 'btn btn-default' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        document_path(document),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>
<br><br>

app/views/documents/edit.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1 class="text-white">Documentos    <%if current_user && current_user.kind == "manager" %>- <%= link_to 'Enviar Documento',
              new_document_path,
              :class => 'btn btn-primary' %></h1><%end%>
  </div>
  <%if current_user && current_user.kind == "manager" %>
    <%= render :partial => 'manager' %>
  <% elsif current_user%>
  <%= render :partial => 'client' %>
  <%end%>
<br><br>

app/views/documents/new.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @document.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= @document.file %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @document.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @document.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<div class="row">
  <div class=" text-center">
    <div class="mz_row">
      <%if current_user && current_user.kind == "manager" %>

      <h1>Olá <%= current_user.name%></h1>
      <br><br><br>
      <div class="col-lg-5 box-home text-black" align="center">
        <img class="rounded-circle" src="icon-users0.png" alt="Icone Clientes" width="100" height="100">
        <h2>Clientes</h2>
        <p>Lista dos clientes cadastrados na plataforma</p><br>
        <a href="accounts"> <button type="button" name="button" class="btn btn-primary">Ver Clientes</button></a>
        <br><br><br>
      </div>

      <div class="col-lg-5 box-home text-black" align="center">
        <img class="rounded-circle" src="icon-documents0.png" alt="Icone Documento" width="180" height="100">
        <h2>Documentos</h2>
        <p>Lista dos documentos cadastrados na plataforma</p><br>
        <a href="/documents"> <button type="button" name="button" class="btn btn-primary">Ver Documentos</button></a>
        <br><br><br>
      </div>
      <% elsif current_user%>

      <h1>Olá <%= current_user.name%></h1><br>
      <div class="col-lg-11 box-home text-black" align="center">
        <img class="rounded-circle" src="icon-documents0.png" alt="Icone Documento" width="180" height="100">
        <h2>Documentos</h2>
        <p>Lista dos documentos cadastrados na plataforma</p><br>
        <a href="/documents"> <button type="button" name="button" class="btn btn-primary">Ver Documentos</button></a>
        <br><br><br>
      </div>
      <%else%>
      <div class="jumbotron">
        <h1 class="jumbotron text-black">Faça Login para usar o Sistema!</h1>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!-- <!DOCTYPE html> -->
<html>
<head>
  <title>Intranet</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="icon" type="image/png" href="img3.png">
  <script src="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Pacifico:400italic,600italic,700italic,400,600,700">
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand logo" href="/">Intranet</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
        <!-- <ul class="nav navbar-nav">
        <li><a href="/insta_users">Contas Instagram</a></li>
        <li><a href="/insta_users">Contas Instagram</a></li>


      </ul> -->
      <% if current_user && current_user.kind == "manager" %>
        <ul class="nav navbar-nav navbar-right">
          <!-- <li><a href="/insta_users"><span class="glyphicon glyphicon-user"></span> Texto 1</a></li>
          <li><a href="/insta_runs"><span class="glyphicon glyphicon-fire"></span> Texto 2</a></li> -->
          <li><a href="/accounts"><span class="glyphicon glyphicon-user"></span> Usuários</a></li>
          <li><a href="/documents"><span class="glyphicon glyphicon-file"></span> Documentos</a></li>
          <li class="active"><%= link_to 'Logout', destroy_user_session_path,:method => :delete%></li>
        </ul>
      <% elsif current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/accounts/<%= current_user.id %>/edit"><span class="glyphicon glyphicon-user"></span> Editar Perfil</a></li>
          <li class="active"><%= link_to 'Logout', destroy_user_session_path,:method => :delete%></li>
        </ul>
      <%else%>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Cadastre-se</a></li> -->
        <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
      <%end%>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>
<!-- <nav class="navbar navbar-default navbar-fixed-top">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>


</div>

</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->

<div class="container"><br><br><br>
  <%= yield %><!--/row-->
</div> <!-- /container -->
</body>
</html>

app/views/users/index.html.erb
<%- model_class = User -%>
<h1 class="text-white">Clientes - <%= link_to 'Cadastrar Cliente',
            "/users/sign_up",
            :class => 'btn btn-primary' %></h1>

  <% @users.each do |user| %>
    <div class="col-lg-4 box text-black" align="center">
      <img class="rounded-circle" src="icon-users0.png" alt="Icone Documento" width="100" height="100">
      <h2><%= user.name %></h2>
      <p><%= user.email %></p>

    </div>
  <% end %>
<br><br>